apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-form-service
  namespace: circleguard-dev
  labels:
    app: circleguard-form-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-form-service
  template:
    metadata:
      labels:
        app: circleguard-form-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: form
          image: ghcr.io/juancasanov/circleguard-form-service:dev-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8380
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: circleguard-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: circleguard-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: circleguard-config
                  key: DB_USERNAME
            - name: FORM_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: circleguard-config
                  key: FORM_DB_URL
            - name: FORM_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: FORM_DB_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: circleguard-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8380
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8380
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-form-service
  namespace: circleguard-dev
  labels:
    app: circleguard-form-service
spec:
  type: ClusterIP
  selector:
    app: circleguard-form-service
  ports:
    - port: 8380
      targetPort: 8380
      protocol: TCP
      name: http
