apiVersion: v1
kind: Service
metadata:
  name: circleguard-auth-service
spec:
  type: ClusterIP
  selector:
    app: circleguard-auth-service
  ports:
    - port: 8180
      targetPort: 8180
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-auth-service
  template:
    metadata:
      labels:
        app: circleguard-auth-service
    spec:
      containers:
        - name: auth
          image: ghcr.io/juancasanov/circleguard-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8180
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: AUTH_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: AUTH_DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: AUTH_JWT_SECRET
            - name: QR_SECRET
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: AUTH_QR_SECRET
            - name: SPRING_LDAP_URLS
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: LDAP_URLS
            - name: SPRING_LDAP_BASE
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: LDAP_BASE
            - name: SPRING_LDAP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: LDAP_USERNAME
            - name: SPRING_LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: LDAP_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8180
            initialDelaySeconds: 45
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8180
            initialDelaySeconds: 45
            periodSeconds: 30
