apiVersion: v1
kind: ConfigMap
metadata:
  name: circleguard-service-config
data:
  HOST_DOCKER_INTERNAL: host-docker-internal
  AUTH_DB_URL: jdbc:postgresql://host-docker-internal:5432/circleguard_auth
  IDENTITY_DB_URL: jdbc:postgresql://host-docker-internal:5432/circleguard_identity
  FORM_DB_URL: jdbc:postgresql://host-docker-internal:5432/circleguard_form
  PROMOTION_DB_URL: jdbc:postgresql://host-docker-internal:5432/circleguard_promotion
  DASHBOARD_DB_URL: jdbc:postgresql://host-docker-internal:5432/circleguard_dashboard
  REDIS_HOST: host-docker-internal
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: host-docker-internal:9092
  NEO4J_URI: bolt://host-docker-internal:7687
  LDAP_URLS: ldap://host-docker-internal:389
  LDAP_BASE: dc=circleguard,dc=edu
  LDAP_USERNAME: cn=admin,dc=circleguard,dc=edu
