apiVersion: v1
kind: Service
metadata:
  name: circleguard-form-service
spec:
  type: ClusterIP
  selector:
    app: circleguard-form-service
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-form-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-form-service
  template:
    metadata:
      labels:
        app: circleguard-form-service
    spec:
      containers:
        - name: form
          image: ghcr.io/juancasanov/circleguard-form-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: FORM_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: FORM_DB_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 45
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 45
            periodSeconds: 30
