apiVersion: v1
kind: Service
metadata:
  name: circleguard-identity-service
spec:
  type: ClusterIP
  selector:
    app: circleguard-identity-service
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-identity-service
  template:
    metadata:
      labels:
        app: circleguard-identity-service
    spec:
      containers:
        - name: identity
          image: ghcr.io/juancasanov/circleguard-identity-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: IDENTITY_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: IDENTITY_DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: IDENTITY_JWT_SECRET
            - name: VAULT_SECRET
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: IDENTITY_VAULT_SECRET
            - name: VAULT_SALT
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: IDENTITY_VAULT_SALT
            - name: VAULT_HASH_SALT
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: IDENTITY_HASH_SALT
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 45
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 45
            periodSeconds: 30
