apiVersion: v1
kind: Service
metadata:
  name: circleguard-promotion-service
spec:
  type: ClusterIP
  selector:
    app: circleguard-promotion-service
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-promotion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-promotion-service
  template:
    metadata:
      labels:
        app: circleguard-promotion-service
    spec:
      containers:
        - name: promotion
          image: ghcr.io/juancasanov/circleguard-promotion-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: PROMOTION_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: PROMOTION_DB_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: REDIS_PORT
            - name: SPRING_NEO4J_URI
              valueFrom:
                configMapKeyRef:
                  name: circleguard-service-config
                  key: NEO4J_URI
            - name: SPRING_NEO4J_AUTHENTICATION_USERNAME
              value: neo4j
            - name: SPRING_NEO4J_AUTHENTICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: NEO4J_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 45
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 45
            periodSeconds: 30
